function opt = nsgaiiOptions(problemSize)

opt.PopulationSize = 50;
opt.ProblemSize = problemSize;
opt.Xmin = 0*ones(1,problemSize);
opt.Xmax = ones(1,problemSize);
opt.Generation = 1;
opt.MaxGeneration = 200;
opt.DominatingSortingType = 'Goldberg'; % Goldberg Fonseca
opt.Selection.Method = 'Tournament';
opt.Selection.TourSize = 4;
opt.Crossover.Method = 'Heuristic'; % Uniform Intermediate Heuristic
opt.Crossover.Dinterm = 0.25;
opt.Crossover.Sheuristic = 0.25;
opt.Mutation.Probability = 1/problemSize;
opt.Mutation.Method = 'Uniform'; %Uniform Gaussian Breeder
opt.Mutation.ScaleGaussian = 1;
opt.Mutation.ShrinkGaussian = 0.1;
opt.StallGenerationLimit = 50;
opt.UniqueSolutionThreshold = 0.00001;
opt.PlotAllFronts = true;